name: Descompactar projeto
on: workflow_dispatch
permissions:
  contents: write
jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Descompactar hellobin.zip
        run: |
          unzip -o hellobin.zip
          rm hellobin.zip
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add -A
          git commit -m "Adiciona o projeto HelloBin"
          git push
